variable "subscription_id" {
  description = "Azure subscription hosting the platform."
  type        = string
}

variable "tenant_id" {
  description = "Entra ID tenant backing the subscription."
  type        = string
}

variable "unique_suffix" {
  description = "Short suffix making globally-unique names deterministic per subscription. Generated by 'make tfvars'."
  type        = string
}

variable "location" {
  description = "Azure region. Sweden Central is the platform's target region and the destination of the YODA migration."
  type        = string
  default     = "swedencentral"
}

variable "operator_ip_ranges" {
  description = "Operator source addresses allowed through the storage, Key Vault and AKS API server ACLs. Generated by 'make tfvars' from the current public IP."
  type        = list(string)
  default     = []
}

variable "domains" {
  description = <<-EOT
    Data domains that get their own Databricks workspace, catalog and Entra
    groups. Append-only: the network module allocates Databricks subnets by
    list index, so reordering this list renumbers existing workspaces.
  EOT
  type        = list(string)
  default     = ["logistics"]
}

variable "budget_alert_emails" {
  description = "Addresses receiving budget and platform alerts."
  type        = list(string)
  default     = []
}

variable "monthly_budget" {
  description = <<-EOT
    Monthly budget in the subscription's **billing currency** — SEK here, not
    EUR. Roughly SEK 550 is the EUR 50 the cost design in docs/FINOPS.md is
    written against. See the note on the governance module's variable of the
    same name.
  EOT
  type        = number
  default     = 550
}

variable "budget_start_date" {
  description = "Budget start, first of a month in RFC3339."
  type        = string
  default     = "2026-08-01T00:00:00Z"
}

variable "platform_admin_object_ids" {
  description = "Object IDs seeded as owners of the platform admin group and granted cluster-admin on AKS."
  type        = list(string)
  default     = []
}

variable "enable_aks" {
  description = <<-EOT
    Whether to create the AKS cluster.

    Separated from the rest because it is the only component that consumes vCPU
    quota, and therefore the only one that can fail on a quota error. Setting
    this false deploys the entire data platform — lake, Databricks, Unity
    Catalog, governance — with no compute at all, which is a legitimate state
    for this environment to sit in between demonstrations.
  EOT
  type        = bool
  default     = true
}
